<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
$this->headLink()->appendStylesheet("https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css");
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css', 'Mason'));
$row_width = $this->columns;
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
$bs_lg_col = 12/$this->columns;
$bs_md_col = max($bs_lg_col, 6);
?>
<div class="container-fluid">
    <div class="row" id="contentPanel">
        <?php
        foreach ($this->resources as $resource):
            $titleText = $this->titleProperty ? $resource->value($this->titleProperty, ['default' => $this->translate('[Untitled]'), 'lang' => $valueLang]) : $resource->displayTitle(null, $valueLang);
            $title = $resource->linkRaw($titleText);
            $subtitle = $this->implodePropertyValues($resource, $this->subtitleProperty);
            $details = $this->detailsProperty ? $this->implodePropertyValues($resource, $this->detailsProperty): '';
            ?>
            <div class="col-sm-12 col-md-<?php echo $bs_md_col ?> col-lg-<?php echo $bs_lg_col ?> pb-4">
                <div class="card mason-configurable-preview" >
                    <div class="row no-gutters d-block mx-auto">
                        <div class="col-12">
                            <?php  echo $resource->linkRaw($this->thumbnail($resource, 'large')); ?>
                        </div>
                        <div class="col-sm-12">
                            <div class="card-body">
                                <p class="card-title pr-md-1 mason-configurable-preview-card-title"><?php echo $title ?></p>
                                <p class="card-text mason-configurable-preview-card-subtitle"><?php echo $subtitle ?></p>
                            <?php if ($details): ?>
                                <hr>
                                <p class="card-text align-middle mason-configurable-preview-card-details"><?php echo $details ?></p>
                            <?php endif ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach;?>
    </div>
</div>
