<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
$this->headLink()->appendStylesheet("https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css");
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css', 'Mason'));
$row_width = $this->columns
?>

<?php
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

//echo $this->partial('common/block-layout/configurable-preview-decks/last-row-fill-sized');
//echo $this->partial('common/block-layout/configurable-preview-decks/last-row-same-sized');
//echo $this->partial('common/block-layout/configurable-preview-decks/horizontal-card/last-row-same-sized');
echo $this->partial('common/block-layout/configurable-preview-decks/horizontal-card/fluid-deck'); ?>
