<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
$this->headLink()->appendStylesheet("https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css");
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css', 'Mason'));

?>

        <?php

        $filterLocale = (bool) $this->siteSetting('filter_locale_values');
        $lang = $this->lang();
        $valueLang = $filterLocale ? [$lang, ''] : null;

        $row_count = -1;
        $row_width = 1;
        foreach ($this->resources as $resource):
            if ($row_count == $row_width) {
                $row_count = 0;
            } else {
                $row_count = $row_count + 1 ;
            }
            $title = '';
            $subtitle = '';
            if ($row_count == 0 ){ ?>
                <div class="preview-block card-deck">
             <?php }
            $title = $this->titleProperty ? $resource->value($this->titleProperty, ['default' => $translate('[Untitled]'), 'lang' => $valueLang]) : $resource->displayTitle(null, $valueLang);
            $valueResource = $resource->value($this->subtitleProperty) ? $resource->value($this->subtitleProperty)->valueResource(): false;
            if ($valueResource){
                $subtitle = $valueResource->linkRaw($valueResource->displayTitle(null, $valueLang));
            } else {
                $subtitle = $this->subtitleProperty ? $resource->value($this->subtitleProperty, ['lang' => $valueLang]) : 'None';

            }

            $linkContent = '';
            //see https://getbootstrap.com/docs/4.3/components/card/#horizontal and https://getbootstrap.com/docs/4.3/components/card/#card-decks
            ?>

        <div class="card mb-3 <?php echo $this->resourceType; ?> resource">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <?php  echo $resource->linkRaw($this->thumbnail($resource, 'square')); ?>
                </div>

                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-title"><?php echo $title ?></p>
                        <p class="card-text"><?php echo $subtitle ?></p>
                    </div>
                </div>
            </div>
        </div>
            <?php if ($row_count == $row_width) {?>
    </div>
            <?php }

         endforeach;
            if ($row_count != $row_width){ ?>
    </div>
            <?php } ?>


</div>
