<style>
    .card-deck .card {
        max-width: calc(<?php echo 100/intval($this->columns)?>% - 30px);
    }

</style>
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card-deck">
                <?php
                $count = 0;
                foreach ($this->resources as $resource):
                    $count+=1;?>

                <!-- 4 of these -->
                <div class="card">
                    <?php  echo $resource->linkRaw($this->thumbnail($resource, 'square')); ?>
                    <div class="card-body">This is the title</div>
                </div>
                   <?php
                    if ($count%$this->columns==0):?>
                        <div class="w-100 py-2"></div>
                    <?php endif; ?>

                <?php endforeach;?>
            </div>
        </div>
    </div>
</div>