<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
$this->headLink()->appendStylesheet("https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css");
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css', 'Mason'));
$row_width = $this->columns;
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
$bs_lg_col = 12/$this->columns;
$bs_md_col = max($bs_lg_col, 6);
?>
<div class="container-fluid">
    <div class="row" id="contentPanel">
    <?php
        foreach ($this->resources as $resource):
            $titleText = $this->titleProperty ? $resource->value($this->titleProperty, ['default' => $this->translate('[Untitled]'), 'lang' => $valueLang]) : $resource->displayTitle(null, $valueLang);
            $title = $resource->linkRaw($titleText);
           //TODO: this need to be a view helper
            $subtitle = '';
            $propertyCounter = 0;
            $propertyCount = count($resource->value($this->subtitleProperty,['all'=>true]));
            if ($propertyCount > 0){
                foreach ($resource->value($this->subtitleProperty,['all'=>true]) as $value){
                    $propertyCounter++;
                    //if this is the last entry, add "and"
                    if ($propertyCounter > 1 && $propertyCounter == $propertyCount){
                        $subtitle.=" and ";
                    }
                    if($value->valueResource()){
                        //if it is a resource, get a link to the resource
                        $subtitle .= $value->valueResource()->linkRaw($value->valueResource()->displayTitle(null, $valueLang));
                    } else {
                        //otherwise, get the text
                        $subtitle .= $value->asHTML();
                    }

                    //if it is a long list, add comma after all but last and penultimate
                    if ($propertyCounter < $propertyCount-1) {
                        $subtitle.=', ';
                    }
                }
            } else {
                $subtitle = 'None';
            }


    ?>
        <div class="col-sm-12 col-md-<?php echo $bs_md_col ?> col-lg-<?php echo $bs_lg_col ?> pb-4">
            <div class="card mason-configurable-preview" >
                <div class="row no-gutters d-sm-flex d-block mx-sm-0 mx-auto">
                    <div class="col-12 d-sm-none ">
                        <?php  echo $resource->linkRaw($this->thumbnail($resource, 'large')); ?>
                    </div>
                    <div class="col-sm-4 d-none d-sm-block my-auto">
                        <?php  echo $resource->linkRaw($this->thumbnail($resource, 'square')); ?>
                    </div>

                    <div class="col-sm-8 my-auto">
                        <div class="card-body pr-lg-1 pr-md-2">
                            <p class="card-title pb-3"><?php echo $title ?></p>
                            <p class="card-text align-middle"><?php echo $subtitle ?></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php endforeach;?>
       </div>
</div>
